[package]
name = "trait_example"
version = "0.1.0"
authors = ["Matt <mboddewy@u.rochester.edu>"]
edition = "2018"

[dependencies]

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"
